run-name: JOB_CLEANUP - ${{ github.event_name }} by @${{ github.actor }}
# name: Fabric Build
concurrency: job-cleanup
on: 
  push:
    branches:    
      - 'arthur/secret-manager'
  pull_request:

  schedule:
    # only runs on default branch
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */12 * * *'

jobs:
  
  Run-Test-Build:
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        test_groups: ['base_defaults']
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: read
      checks: write

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 5